### PR TITLE
Make it possible to just read current_user

### PR DESCRIPTION
**Pull request by anderslemke**
I have a use case, where I want to do A if there is a user, and B if there is no user.

So I need to read the `current_user` without doing anything if it isn't there.

I know you're in the midst of version 2.0, but just wanted to get this idea in here.

### CODE REVIEW

**Comment by nsarno** [comment]
It should definitely be possible to do this. I'll make sure I look at this asap (in the week if everything goes well). Sorry for the delay.

Thanks for contributing! :+1:

**Comment by nsarno** [comment]
This seems like a great solution to me! :+1:

The authentication mechanism will change in the v2 but I'll make sure it is still possible to do this.

I'll be happy to merge this if we can add a few things:

### :wrench:
- [ ] Add some tests (We probably need to create another controller in the dummy test app for this)
- [ ] Replace `split(' ')` by `split` as the default delimiter is already a whitespace
- [ ] Fix conflicts with master

### :book:
- [ ] Update the `CHANGELOG.md`
- [ ] Update the `README.md`

Just let me know if you don't think you'll have time for this and I'll create another PR.

Sorry it took me a bit of time to review!
Cheers

**Comment by anderslemke** [comment]
Hi @nsarno ,

You should be able to check off everything on your list now. :)

I did something slightly different for the `split(' ')`, though, to be more specific.
That's probably how I would have written it, if I had written it in the first place.
I hope you agree that it is better. Otherwise I can change it to `split` in a... you guessed it... split second.

**Comment by nsarno** [comment]
Awesome! We could probably squash this into one commit before I merge it.

**Comment by anderslemke** [comment]
I'll do that. Just a sec.

ons. 30. dec. 2015 kl. 14.28 skrev Arnaud Mesureur <notifications@github.com

**Comment by anderslemke** [comment]
Uhm... I'm not sure how to do that.

The fixed conflict makes me trip over my git-skills.
Any suggestions?

**Comment by nsarno** [comment]
No worries. Master should probably have been rebased instead of merged, then you could have squashed the commits without trouble. I created a new branch, cherry-picked your commits and squashed them (cf #31). Should be all good now :+1: 

I'll release `v1.4` soon with all the recent changes including this, thanks! :)

**Pull request closed without merging**
