### PR TITLE
Feature request (Example of implementation)

### PR DESCRIPTION
**Pull request by thalesfp**
Would be great authenticate more than one model per controller. Example:

before_action :authenticate_admin_or_user_or_other_model

### CODE REVIEW

**Comment by nsarno** [comment]
Thanks for contributing! This is an interesting problem.

I thought about it and I'm not sure I want to implement this. I feel like needing this feature potentially means the controller is too complex and should be separated in two different controllers. This is only a guess and I could be wrong though.

Could you give me a specific example where this would be needed? Thanks

**Comment by thalesfp** [comment]
I'm implementing an Api where Admin can receive (index/show) and modify (new/update/destroy) a model and the User can only receive.

**Comment by nsarno** [comment]
I think it is generally better to have two different controllers in that situation.

Implementing  `authenticate_admin_or_user` would also mean introducing something like `current_admin_or_user` which I find really confusing.

This feature was interesting to think about but I will not implement it as I think there are cleaner ways to deal with that kind of situation.

Thanks again for contributing!

**Comment by thalesfp** [comment]
Thank you for the support. Its true, it could be avoided separating the logic in two controllers, thank you.

**Pull request closed without merging**
