### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by nsarno**
### Upgrade from 1.3

*For everyone*

- Change gem version in Gemfile from '~> 1.3' to '~> 2.0' and run `bundle install`.
- Replace `authenticate` filters with `authenticate_user`.
- Remove this line from   `config/routes.rb`: `mount Knock::Engine => "/knock"`
- Run the token controller generator: `rails g knock:token_controller user`

*For special configurations*

If you have a custom value set for `Knock.handle_attr` AND/OR `Knock.current_user_from_handle`:

- Remove it from the `config/initializers/knock.rb`
- Implement the `User.find_for_token_creation` method in `user.rb`:

Example to use `:username` instead of `:email`:

```ruby
def self.find_for_token_creation params
  User.find_by username: params[:username]
end
```

This method takes the parameters from the controller (`params.require(:auth).permit!`) in argument.
If the user cannot be found, it should return a falsy value (`nil` or `false`).
If you raise an exception here, it is your responsability to rescue it and act accordingly.

If you have a custom value set for `Knock.current_user_from_token`:

- Remove it from the `config/initializers/knock.rb`.
- Implement the `User.find_for_authentication` method in `user.rb`:

Example to retrieve the user id from a field other than 'sub' in the token payload:

```ruby
def self.find_for_authentication payload
  User.find payload['custom_field']
end
```

This method takes the token payload in argument.
If the user cannot be found, it should return a falsly value (`nil` or `false`) or raise an exception.
In both case, knock will respond with `head :unauthorized`.

### Added
- Handle multiple types of user models (useful if you need admin users for example).
- Token controller generator (for signing in): `knock:token_controller`. Multiple user models means we need one token controller per user type.

### Changed
- Rename `Knock::Authenticable` to `Knock::Authenticatable`.
- Rename `authenticate` to `authenticate_user`.
- Use class method `find_for_authentication` in the user model instead of `Knock.current_user_from_token`.
- Use class method `find_for_token_creation` in the user model instead of `Knock.current_user_from_handle` and `Knock.handle_attr`.

### Removed
- `Knock.handle_attr`
- `Knock.current_user_from_handle`
- `Knock.current_user_from_token`
- No need to mount the engine anymore.

### CODE REVIEW

**Comment by feliksg** [comment]
Is this branch still in active development or suitable for use?

**Comment by nsarno** [comment]
@feliksg This branch is still in development. Unfortunately I haven't had much time to make any progress on it lately.

If you're interested in using this branch, feel free to do so (I'd still recommend to use the latest release instead in production). I need to apply some fixes that have been made on the master branch, the rest should work fine and it gives you more features and flexibility.

If you do, don't hesitate to ask any questions or report any issue here. Cheers!

**Comment by feliksg** [comment]
@nsarno Thanks for the update and all of your hard work on this gem!

I'm working on a Rails 5 api project now that needs the multi-model feature from the v2 branch so I went ahead and ran a diff between v2 and master and pulled in all the changes (except for accessing the current_user in the controller without being authenticated, i'm not sure what that is used for).

You can see my branch [here](https://github.com/feliksg/knock/tree/migrate-fixes-from-master).  I can create a pull request if you'd like to merge it in.

**Comment by nsarno** [comment]
@feliksg I'll have a look at it asap. Thank you for your help and the kind words.

**Comment by cjeffries** [comment]
@feliksg I've started using your migrate-fixes-from-master branch on a personal fork (so you can make any changes you want and it won't affect my code) in a project and, thus far, it seems to work great for multi-model authentication. Thanks for performing that merge.

Thank you to @nsarno as well for all your hard work on Knock and more specifically, the 2.0 version here. Looking forward to when 2.0 is officially released.

**Comment by nsarno** [comment]
@cjeffries I'm determined to make that happening soon. Thank you for testing the v2, really appreciate the feedback :+1:

**Comment by onemanstartup** [comment]
Hi @nsarno, could you in new version do not hardcode name of the response object like jwt? I wanted to be more meaningful for the end user like access_token. 
```ruby
{jwt: @token}.to_json
```
If it seems irrational please explain why I'm wrong.  Thanks.

**Comment by nsarno** [comment]
@onemanstartup The v2 should already allow you to format the response however you want by overriding the controller. However I agree we could improve the response to make it more meaningful by default. Sorry for the late reply.

**Comment by gustavovnicius** [comment]
When it'll be merged on master (and published on rubygems) ? I'm needing these features =/ If there is any way that I can help....

**Comment by nsarno** [comment]
@gustavovnicius This branch has been here for a long time for a few reason. I haven't had as much time as I wanted to take care of it but mostly I didn't want to introduce so many breaking changes without more feedback from people using the gem.

I don't actually intend to ever merge this PR at once but instead introduce as many as these features as possible into the v1 in a non-breaking way. Then release the v2 by removing deprecated v1 code.

I actually planned to work on this in the coming days. Any feedback about this v2 would be greatly appreciated!

**Comment by nsarno** [comment]
@gustavovnicius Thanks for your help with this! I'm closing it in favor of #72. Considering your frequent contributions, I would love for you to review #72 before it is merged to master.

I think it should provide a solid ground for implementing more features with a better design, like custom claims.

Cheers!

**Comment by mesge** [comment]
Hey there @nsarno, awesome work on this gem! I am actually using the v2 branch for a pet project. I know it will never be merged in and it's on my todo list to migrate to the official release in #72 - was wondering how compatible the two branches are with each other as I initially chose to pull from v2 due to its support for multiple authenticated resources. If significant parts of this feature are incompatible I'd be keen to fork this branch until I find the time to make the change.

**Pull request closed without merging**
