### PR TITLE
make ActiveRecord::NotFound exception configurable

### PR DESCRIPTION
**Pull request by eturino**
in order to use other exceptions, if no ActiveRecord is used.

### CODE REVIEW

**Comment by eturino** [comment]
I don't understand why it fails in Travis. It passes for me with rubies 2.1.7 and 2.3.0

**Comment by eturino** [comment]
after adding 2 more versions to Travis and no other change, now 2.1.0 runs ok but 2.1.7 fails... sigh...

**Comment by colinramsay** [comment]
Is this the only thing preventing Knock from being independent of Active Record?

**Comment by eturino** [comment]
@colinramsay I am using this in an rails 5 API with no ActiveRecord and it is fine so far.

**Comment by nsarno** [comment]
@eturino Thank you for this. I was hoping to come up with a solution other than configuration for this but I haven't had time to work on it yet.

Could you rebase this into one commit before I merge it? Thanks 👍

**Comment by eturino** [comment]
@nsarno I think you can use the new Github feature of "Squash and merge". I've been using them at work for quite some time now.

https://github.com/blog/2141-squash-your-commits

**Pull request merged**
