### PR TITLE
v2.2

### PR DESCRIPTION
**Pull request by nsarno**
Draft Pull Request for v2.2

Feel free to comment with links to issues or changes you believe should be added to this version.

### Changes

- Update the dependencies
- Remove the generators
- Fix deprecation warnings and autoloading

### CODE REVIEW

**Comment by FunkyloverOne** [comment]
hey @nsarno, please take a look at this one: https://github.com/nsarno/knock/issues/240

And here's how people suggest to fix it to work nicely with Zeitwerk: https://github.com/rails/rails/issues/36381#issuecomment-511185972

**Comment by nsarno** [comment]
@FunkyloverOne I've made some changes to address the issue.

Here is what I get when running the zeitwerk check in a Rails 6.0.1 app with Knock install from this branch.

```
$ bin/rails zeitwerk:check
Hold on, I am eager loading the application.
All is good!
```

**Comment by andrerpbts** [comment]
Hello @nsarno 

Here are some issues I think would be welcome on 2.2:

- https://github.com/nsarno/knock/issues/228 -> It seems to be a security flaw, and it isn't the first time I saw an issue involving a problem with this method (https://github.com/nsarno/knock/issues/220). There's a PR related with this that would solve the problem, but I think we probably can change it from using method missing strategy and turn it more configurable...

- https://github.com/nsarno/knock/issues/226 -> Probably it's already in the map, but I think we could use API controller in the place of the base controller...

- https://github.com/nsarno/knock/issues/183 -> This is a thing I had some problems when I used Knock recently. I wanted to authenticate with document and password, and I turned it back to email instead patching the method like docs suggested. Like in devise, where you can set what fields the user is going to be identified, I think that would be a good move for us as well. We can simply add an entry into knock configuration file, let it default to email, and use that fields to enforce params and seek the user. 

I think that's it... What do you think?

**Comment by Lax** [comment]
Hi, I'm here to asking when will this update version been published? Now my rails 6.0 project is having some mentioned issues that would be fixed by this PR.

**Comment by nsarno** [comment]
@andrerpbts 

> #228 -> It seems to be a security flaw, and it isn't the first time I saw an issue involving a problem with this method (#220). There's a PR related with this that would solve the problem, but I think we probably can change it from using method missing strategy and turn it more configurable...

For now, we can simply update the doc. Ultimately, I would like to move away from relying on `method_missing` but this would probably be part of a major version release.

I'll try to address the other issues in this version.

@lax I'm aiming at releasing it this month.

**Comment by maxrosecollins** [comment]
@nsarno When will this be released? Thanks!

**Comment by nsarno** [comment]
@maxrosecollins This looks ready actually. I was hoping to fix some other issues as part of this version but I didn't get to it so I'll just merge it as is for now.

**Comment by nsarno** [comment]
@maxrosecollins master is green again, good times. Thanks for the gentle ping.

If you (or anyone else here) test their project with the new master and can confirm everything is working well, that would be greatly appreciated and would give me some extra confidence to release the new version to RubyGems. Cheers!

**Comment by swrobel** [comment]
@nsarno still don't see this on rubygems...

**Comment by nsarno** [comment]
@swrobel are you confirming that you've tested the new master, think it's working great and validating I can ship this to RubyGems? Or is this just your polite way to point out I'm not doing this unpaid job fast enough for you.

**Comment by swrobel** [comment]
Would you mind tagging v2.2 at least? I'd be happy to test in that case, but I'm not going to just add master to my Gemfile willy-nilly.

**Comment by maxrosecollins** [comment]
@nsarno It seems to run smoothly locally but when I put it into my production environment, I'm getting the following error. I'm not sure if that just something I've done wrong...

`TypeError (no implicit conversion of nil into String):
app/controllers/api/v1/user_token_controller.rb:8:in `create'`

This line is 
`
user = User.find(auth_token.payload[:sub])
`

**Comment by maxrosecollins** [comment]
@nsarno Okay my mistake, I had `Rails.application.secrets.secret_key_base` insead of `Rails.application.credentials.secret_key_base`

**Comment by dtgay** [comment]
@swrobel I don't think you have to add `master` willy-nilly, you can specify a commit like so:
```
gem "knock", git: "https://github.com/nsarno/knock", branch: "master",
    ref: "9214cd027422df8dc31eb67c60032fbbf8fc100b"
```

**Comment by dtgay** [comment]
@nsarno Great work, I'm successfully using knock at commit `9214cd027422df8dc31eb67c60032fbbf8fc100b` in my Rails 6 API. Consider it a :+1: from me. And thanks!

For anyone trying to get things working in their own app, I wrote a blog post explaining how I did things: https://davidgay.org/software/jwt-auth-rails-6-knock/

**Comment by maxrosecollins** [comment]
@nsarno It's working smoothly for me in prod too 👍

**Comment by jusantana** [comment]
Working nice for me as well. Thank you @dtgay for the guide!

**Pull request merged**
