### PR TITLE
Bump JWT dependency to 2.2.1

### PR DESCRIPTION
**Pull request by wkurosawa**
An attempt to update the JWT gem dependency as other gems that I want to use are having conflicts.

### CODE REVIEW

**Comment by wkurosawa** [comment]
Uh, sorry for all this choppy updates, I keep bumping into small problems. I should've opened the PR after being sure that everything was working correctly, but my initial concern was to make the Travis CI pass.

**Comment by FunkyloverOne** [comment]
hey @wkurosawa, you did a good job here! thank you!
@nsarno how about to merge this one? it will fix CI check for all the other PR's if they will perform a rebase on top of it.

**Comment by wkurosawa** [comment]
@nsarno Any comments on this? I've been using with Auth0 in production since when I opened the PR. So far so good, but let me know if it should have any other changes in this PR.

**Comment by nsarno** [comment]
@wkurosawa Thank you.

**Pull request merged**
